# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.intraday_api import IntradayApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntradayApi(unittest.TestCase):
    """IntradayApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.intraday_api.IntradayApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_intraday_get_by_default(self):
        """Test case for intraday_get_by_default

        """
        pass

    def test_intraday_get_by_id(self):
        """Test case for intraday_get_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
