# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.activity_summay_summary1_heart_rate_zones import ActivitySummaySummary1HeartRateZones  # noqa: E501
from swagger_client.rest import ApiException


class TestActivitySummaySummary1HeartRateZones(unittest.TestCase):
    """ActivitySummaySummary1HeartRateZones unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivitySummaySummary1HeartRateZones(self):
        """Test ActivitySummaySummary1HeartRateZones"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.activity_summay_summary1_heart_rate_zones.ActivitySummaySummary1HeartRateZones()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
