# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.devices_api import DevicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDevicesApi(unittest.TestCase):
    """DevicesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.devices_api.DevicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_device_by_id(self):
        """Test case for add_device_by_id

        """
        pass

    def test_add_profile_by_id(self):
        """Test case for add_profile_by_id

        """
        pass

    def test_get_device_list(self):
        """Test case for get_device_list

        """
        pass

    def test_get_profile_by_id(self):
        """Test case for get_profile_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
