# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cura_score_values1 import CuraScoreValues1  # noqa: E501
from swagger_client.rest import ApiException


class TestCuraScoreValues1(unittest.TestCase):
    """CuraScoreValues1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCuraScoreValues1(self):
        """Test CuraScoreValues1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cura_score_values1.CuraScoreValues1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
