# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.manager_api import ManagerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManagerApi(unittest.TestCase):
    """ManagerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.manager_api.ManagerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cura_by_users(self):
        """Test case for get_cura_by_users

        """
        pass


if __name__ == '__main__':
    unittest.main()
