# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.activity_sleep_levels1_data import ActivitySleepLevels1Data  # noqa: E501
from swagger_client.rest import ApiException


class TestActivitySleepLevels1Data(unittest.TestCase):
    """ActivitySleepLevels1Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivitySleepLevels1Data(self):
        """Test ActivitySleepLevels1Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.activity_sleep_levels1_data.ActivitySleepLevels1Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
