# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2003_activitieslog import InlineResponse2003Activitieslog  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2003Activitieslog(unittest.TestCase):
    """InlineResponse2003Activitieslog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003Activitieslog(self):
        """Test InlineResponse2003Activitieslog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2003_activitieslog.InlineResponse2003Activitieslog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
