# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.intraday_logentry import IntradayLogentry  # noqa: E501
from swagger_client.rest import ApiException


class TestIntradayLogentry(unittest.TestCase):
    """IntradayLogentry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntradayLogentry(self):
        """Test IntradayLogentry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.intraday_logentry.IntradayLogentry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
