# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cura_score import CuraScore  # noqa: E501
from swagger_client.rest import ApiException


class TestCuraScore(unittest.TestCase):
    """CuraScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCuraScore(self):
        """Test CuraScore"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cura_score.CuraScore()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
