# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.summary_api import SummaryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSummaryApi(unittest.TestCase):
    """SummaryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.summary_api.SummaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activity_summary_get_by_id(self):
        """Test case for activity_summary_get_by_id

        """
        pass

    def test_activity_summary_get_by_id_date(self):
        """Test case for activity_summary_get_by_id_date

        """
        pass


if __name__ == '__main__':
    unittest.main()
