# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.activity_summay_goals1 import ActivitySummayGoals1  # noqa: E501
from swagger_client.rest import ApiException


class TestActivitySummayGoals1(unittest.TestCase):
    """ActivitySummayGoals1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivitySummayGoals1(self):
        """Test ActivitySummayGoals1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.activity_summay_goals1.ActivitySummayGoals1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
