# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.activity_summay_activities import ActivitySummayActivities  # noqa: E501
from swagger_client.rest import ApiException


class TestActivitySummayActivities(unittest.TestCase):
    """ActivitySummayActivities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivitySummayActivities(self):
        """Test ActivitySummayActivities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.activity_summay_activities.ActivitySummayActivities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
