# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cura_score_api import CuraScoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCuraScoreApi(unittest.TestCase):
    """CuraScoreApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cura_score_api.CuraScoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cura_by_id(self):
        """Test case for get_cura_by_id

        """
        pass

    def test_get_cura_ex_by_id(self):
        """Test case for get_cura_ex_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
