# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.activity_sleep_sleep1 import ActivitySleepSleep1  # noqa: E501
from swagger_client.rest import ApiException


class TestActivitySleepSleep1(unittest.TestCase):
    """ActivitySleepSleep1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivitySleepSleep1(self):
        """Test ActivitySleepSleep1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.activity_sleep_sleep1.ActivitySleepSleep1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
