# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ActivitySleepLevels(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'summary': 'ActivitySleepLevels1Summary',
        'data': 'list[ActivitySleepLevels1Data]',
        'short_data': 'list[ActivitySleepLevels1Data]'
    }

    attribute_map = {
        'summary': 'summary',
        'data': 'data',
        'short_data': 'shortData'
    }

    def __init__(self, summary=None, data=None, short_data=None):  # noqa: E501
        """ActivitySleepLevels - a model defined in Swagger"""  # noqa: E501

        self._summary = None
        self._data = None
        self._short_data = None
        self.discriminator = None

        if summary is not None:
            self.summary = summary
        self.data = data
        self.short_data = short_data

    @property
    def summary(self):
        """Gets the summary of this ActivitySleepLevels.  # noqa: E501


        :return: The summary of this ActivitySleepLevels.  # noqa: E501
        :rtype: ActivitySleepLevels1Summary
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this ActivitySleepLevels.


        :param summary: The summary of this ActivitySleepLevels.  # noqa: E501
        :type: ActivitySleepLevels1Summary
        """

        self._summary = summary

    @property
    def data(self):
        """Gets the data of this ActivitySleepLevels.  # noqa: E501


        :return: The data of this ActivitySleepLevels.  # noqa: E501
        :rtype: list[ActivitySleepLevels1Data]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ActivitySleepLevels.


        :param data: The data of this ActivitySleepLevels.  # noqa: E501
        :type: list[ActivitySleepLevels1Data]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def short_data(self):
        """Gets the short_data of this ActivitySleepLevels.  # noqa: E501


        :return: The short_data of this ActivitySleepLevels.  # noqa: E501
        :rtype: list[ActivitySleepLevels1Data]
        """
        return self._short_data

    @short_data.setter
    def short_data(self, short_data):
        """Sets the short_data of this ActivitySleepLevels.


        :param short_data: The short_data of this ActivitySleepLevels.  # noqa: E501
        :type: list[ActivitySleepLevels1Data]
        """
        if short_data is None:
            raise ValueError("Invalid value for `short_data`, must not be `None`")  # noqa: E501

        self._short_data = short_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActivitySleepLevels, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActivitySleepLevels):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
