# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ActivitySummaySummary1HeartRateZones(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'calories_out': 'int',
        'max': 'int',
        'min': 'int',
        'minutes': 'int',
        'name': 'str'
    }

    attribute_map = {
        'calories_out': 'caloriesOut',
        'max': 'max',
        'min': 'min',
        'minutes': 'minutes',
        'name': 'name'
    }

    def __init__(self, calories_out=None, max=None, min=None, minutes=None, name=None):  # noqa: E501
        """ActivitySummaySummary1HeartRateZones - a model defined in Swagger"""  # noqa: E501

        self._calories_out = None
        self._max = None
        self._min = None
        self._minutes = None
        self._name = None
        self.discriminator = None

        if calories_out is not None:
            self.calories_out = calories_out
        if max is not None:
            self.max = max
        if min is not None:
            self.min = min
        if minutes is not None:
            self.minutes = minutes
        if name is not None:
            self.name = name

    @property
    def calories_out(self):
        """Gets the calories_out of this ActivitySummaySummary1HeartRateZones.  # noqa: E501


        :return: The calories_out of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :rtype: int
        """
        return self._calories_out

    @calories_out.setter
    def calories_out(self, calories_out):
        """Sets the calories_out of this ActivitySummaySummary1HeartRateZones.


        :param calories_out: The calories_out of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :type: int
        """

        self._calories_out = calories_out

    @property
    def max(self):
        """Gets the max of this ActivitySummaySummary1HeartRateZones.  # noqa: E501


        :return: The max of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this ActivitySummaySummary1HeartRateZones.


        :param max: The max of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :type: int
        """

        self._max = max

    @property
    def min(self):
        """Gets the min of this ActivitySummaySummary1HeartRateZones.  # noqa: E501


        :return: The min of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min):
        """Sets the min of this ActivitySummaySummary1HeartRateZones.


        :param min: The min of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :type: int
        """

        self._min = min

    @property
    def minutes(self):
        """Gets the minutes of this ActivitySummaySummary1HeartRateZones.  # noqa: E501


        :return: The minutes of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :rtype: int
        """
        return self._minutes

    @minutes.setter
    def minutes(self, minutes):
        """Sets the minutes of this ActivitySummaySummary1HeartRateZones.


        :param minutes: The minutes of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :type: int
        """

        self._minutes = minutes

    @property
    def name(self):
        """Gets the name of this ActivitySummaySummary1HeartRateZones.  # noqa: E501


        :return: The name of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActivitySummaySummary1HeartRateZones.


        :param name: The name of this ActivitySummaySummary1HeartRateZones.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActivitySummaySummary1HeartRateZones, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActivitySummaySummary1HeartRateZones):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
