# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenantid': 'int',
        'userid': 'int',
        'deviceid': 'str',
        'access_token': 'str',
        'refresh_token': 'str',
        'expires': 'int'
    }

    attribute_map = {
        'tenantid': 'tenantid',
        'userid': 'userid',
        'deviceid': 'deviceid',
        'access_token': 'access_token',
        'refresh_token': 'refresh_token',
        'expires': 'expires'
    }

    def __init__(self, tenantid=None, userid=None, deviceid=None, access_token=None, refresh_token=None, expires=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501

        self._tenantid = None
        self._userid = None
        self._deviceid = None
        self._access_token = None
        self._refresh_token = None
        self._expires = None
        self.discriminator = None

        self.tenantid = tenantid
        self.userid = userid
        self.deviceid = deviceid
        self.access_token = access_token
        self.refresh_token = refresh_token
        self.expires = expires

    @property
    def tenantid(self):
        """Gets the tenantid of this InlineResponse200.  # noqa: E501


        :return: The tenantid of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._tenantid

    @tenantid.setter
    def tenantid(self, tenantid):
        """Sets the tenantid of this InlineResponse200.


        :param tenantid: The tenantid of this InlineResponse200.  # noqa: E501
        :type: int
        """
        if tenantid is None:
            raise ValueError("Invalid value for `tenantid`, must not be `None`")  # noqa: E501

        self._tenantid = tenantid

    @property
    def userid(self):
        """Gets the userid of this InlineResponse200.  # noqa: E501


        :return: The userid of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """Sets the userid of this InlineResponse200.


        :param userid: The userid of this InlineResponse200.  # noqa: E501
        :type: int
        """
        if userid is None:
            raise ValueError("Invalid value for `userid`, must not be `None`")  # noqa: E501

        self._userid = userid

    @property
    def deviceid(self):
        """Gets the deviceid of this InlineResponse200.  # noqa: E501


        :return: The deviceid of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._deviceid

    @deviceid.setter
    def deviceid(self, deviceid):
        """Sets the deviceid of this InlineResponse200.


        :param deviceid: The deviceid of this InlineResponse200.  # noqa: E501
        :type: str
        """
        if deviceid is None:
            raise ValueError("Invalid value for `deviceid`, must not be `None`")  # noqa: E501

        self._deviceid = deviceid

    @property
    def access_token(self):
        """Gets the access_token of this InlineResponse200.  # noqa: E501


        :return: The access_token of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this InlineResponse200.


        :param access_token: The access_token of this InlineResponse200.  # noqa: E501
        :type: str
        """
        if access_token is None:
            raise ValueError("Invalid value for `access_token`, must not be `None`")  # noqa: E501

        self._access_token = access_token

    @property
    def refresh_token(self):
        """Gets the refresh_token of this InlineResponse200.  # noqa: E501


        :return: The refresh_token of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this InlineResponse200.


        :param refresh_token: The refresh_token of this InlineResponse200.  # noqa: E501
        :type: str
        """
        if refresh_token is None:
            raise ValueError("Invalid value for `refresh_token`, must not be `None`")  # noqa: E501

        self._refresh_token = refresh_token

    @property
    def expires(self):
        """Gets the expires of this InlineResponse200.  # noqa: E501


        :return: The expires of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this InlineResponse200.


        :param expires: The expires of this InlineResponse200.  # noqa: E501
        :type: int
        """
        if expires is None:
            raise ValueError("Invalid value for `expires`, must not be `None`")  # noqa: E501

        self._expires = expires

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
