# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2003(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'activities_log': 'list[InlineResponse2003Activitieslog]'
    }

    attribute_map = {
        'activities_log': 'activities-log'
    }

    def __init__(self, activities_log=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger"""  # noqa: E501

        self._activities_log = None
        self.discriminator = None

        self.activities_log = activities_log

    @property
    def activities_log(self):
        """Gets the activities_log of this InlineResponse2003.  # noqa: E501


        :return: The activities_log of this InlineResponse2003.  # noqa: E501
        :rtype: list[InlineResponse2003Activitieslog]
        """
        return self._activities_log

    @activities_log.setter
    def activities_log(self, activities_log):
        """Sets the activities_log of this InlineResponse2003.


        :param activities_log: The activities_log of this InlineResponse2003.  # noqa: E501
        :type: list[InlineResponse2003Activitieslog]
        """
        if activities_log is None:
            raise ValueError("Invalid value for `activities_log`, must not be `None`")  # noqa: E501

        self._activities_log = activities_log

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2003, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
