# coding: utf-8

"""
    Curaegis Egress API

    Curaegis egress data API  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Profile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenantid': 'int',
        'userid': 'int',
        'profiledata': 'object'
    }

    attribute_map = {
        'tenantid': 'tenantid',
        'userid': 'userid',
        'profiledata': 'profiledata'
    }

    def __init__(self, tenantid=None, userid=None, profiledata=None):  # noqa: E501
        """Profile - a model defined in Swagger"""  # noqa: E501

        self._tenantid = None
        self._userid = None
        self._profiledata = None
        self.discriminator = None

        self.tenantid = tenantid
        self.userid = userid
        self.profiledata = profiledata

    @property
    def tenantid(self):
        """Gets the tenantid of this Profile.  # noqa: E501


        :return: The tenantid of this Profile.  # noqa: E501
        :rtype: int
        """
        return self._tenantid

    @tenantid.setter
    def tenantid(self, tenantid):
        """Sets the tenantid of this Profile.


        :param tenantid: The tenantid of this Profile.  # noqa: E501
        :type: int
        """
        if tenantid is None:
            raise ValueError("Invalid value for `tenantid`, must not be `None`")  # noqa: E501

        self._tenantid = tenantid

    @property
    def userid(self):
        """Gets the userid of this Profile.  # noqa: E501


        :return: The userid of this Profile.  # noqa: E501
        :rtype: int
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """Sets the userid of this Profile.


        :param userid: The userid of this Profile.  # noqa: E501
        :type: int
        """
        if userid is None:
            raise ValueError("Invalid value for `userid`, must not be `None`")  # noqa: E501

        self._userid = userid

    @property
    def profiledata(self):
        """Gets the profiledata of this Profile.  # noqa: E501


        :return: The profiledata of this Profile.  # noqa: E501
        :rtype: object
        """
        return self._profiledata

    @profiledata.setter
    def profiledata(self, profiledata):
        """Sets the profiledata of this Profile.


        :param profiledata: The profiledata of this Profile.  # noqa: E501
        :type: object
        """
        if profiledata is None:
            raise ValueError("Invalid value for `profiledata`, must not be `None`")  # noqa: E501

        self._profiledata = profiledata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Profile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Profile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
